/*
 * imports.c — WASM import definitions table (copied from bas2wasm)
 */
#include "c2wasm.h"

#define _I WASM_I32
#define _F WASM_F32
#define _D WASM_F64
ImportDef imp_defs[IMP_COUNT] = {
    [IMP_DELAY_MS]      = {"delay_ms",      1,{_I},            0,{}},
    [IMP_MILLIS]         = {"millis",         0,{},              1,{_I}},
    [IMP_GET_PARAM]      = {"get_param",      1,{_I},            1,{_I}},
    [IMP_SET_PARAM]      = {"set_param",      2,{_I,_I},         0,{}},
    [IMP_SHOULD_STOP]    = {"should_stop",    0,{},              1,{_I}},
    [IMP_LED_SET_PIXEL]  = {"led_set_pixel",  5,{_I,_I,_I,_I,_I},0,{}},
    [IMP_LED_FILL]       = {"led_fill",       4,{_I,_I,_I,_I},   0,{}},
    [IMP_LED_SHOW]       = {"led_show",       0,{},              0,{}},
    [IMP_LED_COUNT]      = {"led_count",      1,{_I},            1,{_I}},
    [IMP_LED_GAMMA8]     = {"led_gamma8",     1,{_I},            1,{_I}},
    [IMP_LED_SET_GAMMA]  = {"led_set_gamma",  1,{_I},            0,{}},
    [IMP_LED_SET_BUFFER] = {"led_set_buffer", 3,{_I,_I,_I},      0,{}},
    [IMP_LED_SHIFT]      = {"led_shift",      5,{_I,_I,_I,_I,_I},0,{}},
    [IMP_LED_ROTATE]     = {"led_rotate",     2,{_I,_I},         0,{}},
    [IMP_LED_REVERSE]    = {"led_reverse",    1,{_I},            0,{}},
    [IMP_LED_SET_PIXEL_HSV]={"led_set_pixel_hsv",5,{_I,_I,_I,_I,_I},0,{}},
    [IMP_LED_FILL_HSV]   = {"led_fill_hsv",   4,{_I,_I,_I,_I},   0,{}},
    [IMP_HSV_TO_RGB]     = {"hsv_to_rgb",     3,{_I,_I,_I},      1,{_I}},
    [IMP_RGB_TO_HSV]     = {"rgb_to_hsv",     3,{_I,_I,_I},      1,{_I}},
    [IMP_HOST_PRINTF]    = {"host_printf",    2,{_I,_I},         1,{_I}},
    [IMP_PRINT_I32]      = {"print_i32",      1,{_I},            0,{}},
    [IMP_PRINT_F32]      = {"print_f32",      1,{_F},            0,{}},
    [IMP_PRINT_STR]      = {"print_str",      2,{_I,_I},         0,{}},
    [IMP_GPS_VALID]      = {"gps_valid",      0,{},              1,{_I}},
    [IMP_HAS_ORIGIN]     = {"has_origin",     0,{},              1,{_I}},
    [IMP_ORIGIN_DIST]    = {"origin_dist",    0,{},              1,{_F}},
    [IMP_ORIGIN_BEARING] = {"origin_bearing", 0,{},              1,{_F}},
    [IMP_GET_LAT]        = {"get_lat",        0,{},              1,{_F}},
    [IMP_GET_LON]        = {"get_lon",        0,{},              1,{_F}},
    [IMP_GET_ALT]        = {"get_alt",        0,{},              1,{_F}},
    [IMP_GET_SPEED]      = {"get_speed",      0,{},              1,{_F}},
    [IMP_GET_DIR]         = {"get_dir",         0,{},              1,{_F}},
    [IMP_GET_SECOND]     = {"get_second",     0,{},              1,{_I}},
    [IMP_GET_MINUTE]     = {"get_minute",     0,{},              1,{_I}},
    [IMP_GET_HOUR]       = {"get_hour",       0,{},              1,{_I}},
    [IMP_GET_DAY]        = {"get_day",        0,{},              1,{_I}},
    [IMP_GET_MONTH]      = {"get_month",      0,{},              1,{_I}},
    [IMP_GET_YEAR]       = {"get_year",       0,{},              1,{_I}},
    [IMP_GET_DAY_OF_WEEK]= {"get_day_of_week",0,{},             1,{_I}},
    [IMP_GET_DAY_OF_YEAR]= {"get_day_of_year",0,{},             1,{_I}},
    [IMP_GET_IS_LEAP_YEAR]={"get_is_leap_year",0,{},            1,{_I}},
    [IMP_TIME_VALID]     = {"time_valid",     0,{},              1,{_I}},
    [IMP_IMU_VALID]      = {"imu_valid",      0,{},              1,{_I}},
    [IMP_GET_PITCH]      = {"get_pitch",      0,{},              1,{_F}},
    [IMP_GET_ROLL]       = {"get_roll",       0,{},              1,{_F}},
    [IMP_GET_YAW]        = {"get_yaw",        0,{},              1,{_F}},
    [IMP_GET_ACC_X]      = {"get_acc_x",      0,{},              1,{_F}},
    [IMP_GET_ACC_Y]      = {"get_acc_y",      0,{},              1,{_F}},
    [IMP_GET_ACC_Z]      = {"get_acc_z",      0,{},              1,{_F}},
    [IMP_GET_TEMP]       = {"get_temp",       0,{},              1,{_F}},
    [IMP_GET_HUMIDITY]   = {"get_humidity",   0,{},              1,{_F}},
    [IMP_GET_BRIGHTNESS] = {"get_brightness", 0,{},              1,{_F}},
    [IMP_RANDOM_INT]     = {"random_int",     2,{_I,_I},         1,{_I}},
    [IMP_SINF]           = {"sinf",           1,{_F},            1,{_F}},
    [IMP_COSF]           = {"cosf",           1,{_F},            1,{_F}},
    [IMP_ATAN2F]         = {"atan2f",         2,{_F,_F},         1,{_F}},
    [IMP_POWF]           = {"powf",           2,{_F,_F},         1,{_F}},
    [IMP_LUT_LOAD]       = {"lut_load",       1,{_I},            1,{_I}},
    [IMP_LUT_SAVE]       = {"lut_save",       1,{_I},            1,{_I}},
    [IMP_LUT_CHECK]      = {"lut_check",      1,{_I},            1,{_I}},
    [IMP_LUT_GET]        = {"lut_get",        1,{_I},            1,{_I}},
    [IMP_LUT_SET]        = {"lut_set",        2,{_I,_I},         0,{}},
    [IMP_LUT_SIZE]       = {"lut_size",       0,{},              1,{_I}},
    [IMP_WAIT_PPS]       = {"wait_pps",       1,{_I},            1,{_I}},
    [IMP_WAIT_PARAM]     = {"wait_param",     4,{_I,_I,_I,_I},   1,{_I}},
    [IMP_CUE_PLAYING]    = {"cue_playing",    0,{},              1,{_I}},
    [IMP_CUE_ELAPSED]    = {"cue_elapsed",    0,{},              1,{_I}},
    [IMP_GET_BAT_VOLTAGE]= {"get_bat_voltage",0,{},              1,{_F}},
    [IMP_GET_SOLAR_VOLTAGE]={"get_solar_voltage",0,{},           1,{_F}},
    [IMP_GET_SUNRISE]    = {"get_sunrise",    0,{},              1,{_I}},
    [IMP_GET_SUNSET]     = {"get_sunset",     0,{},              1,{_I}},
    [IMP_SUN_VALID]      = {"sun_valid",      0,{},              1,{_I}},
    [IMP_IS_DAYLIGHT]    = {"is_daylight",    0,{},              1,{_I}},
    [IMP_PIN_SET]        = {"pin_set",        1,{_I},            0,{}},
    [IMP_PIN_CLEAR]      = {"pin_clear",      1,{_I},            0,{}},
    [IMP_PIN_READ]       = {"pin_read",       1,{_I},            1,{_I}},
    [IMP_ANALOG_READ]    = {"analog_read",    1,{_I},            1,{_I}},
    [IMP_GPS_PRESENT]    = {"gps_present",    0,{},              1,{_I}},
    [IMP_IMU_PRESENT]    = {"imu_present",    0,{},              1,{_I}},
    [IMP_GET_BATTERY_PERCENTAGE]={"get_battery_percentage",0,{}, 1,{_F}},
    [IMP_GET_BATTERY_RUNTIME]={"get_battery_runtime",0,{},       1,{_F}},
    [IMP_GET_SUN_AZIMUTH]= {"get_sun_azimuth",0,{},             1,{_F}},
    [IMP_GET_SUN_ELEVATION]={"get_sun_elevation",0,{},           1,{_F}},
    [IMP_FMODF]          = {"fmodf",                2,{_F,_F},         1,{_F}},
    [IMP_TANF]           = {"tanf",                 1,{_F},            1,{_F}},
    [IMP_EXPF]           = {"expf",                 1,{_F},            1,{_F}},
    [IMP_LOGF]           = {"logf",                 1,{_F},            1,{_F}},
    [IMP_LOG2F]          = {"log2f",                1,{_F},            1,{_F}},
    [IMP_ASINF]          = {"asinf",                1,{_F},            1,{_F}},
    [IMP_ACOSF]          = {"acosf",                1,{_F},            1,{_F}},
    [IMP_ATANF]          = {"atanf",                1,{_F},            1,{_F}},
    [IMP_GET_ORIGIN_LAT] = {"get_origin_lat",       0,{},              1,{_F}},
    [IMP_GET_ORIGIN_LON] = {"get_origin_lon",       0,{},              1,{_F}},
    [IMP_FILE_OPEN]      = {"file_open",            3,{_I,_I,_I},      1,{_I}},
    [IMP_FILE_CLOSE]     = {"file_close",           1,{_I},            0,{}},
    [IMP_FILE_READ]      = {"file_read",            3,{_I,_I,_I},      1,{_I}},
    [IMP_FILE_WRITE]     = {"file_write",           3,{_I,_I,_I},      1,{_I}},
    [IMP_FILE_SIZE]      = {"file_size",            1,{_I},            1,{_I}},
    [IMP_FILE_SEEK]      = {"file_seek",            2,{_I,_I},         1,{_I}},
    [IMP_FILE_TELL]      = {"file_tell",            1,{_I},            1,{_I}},
    [IMP_FILE_EXISTS]    = {"file_exists",          2,{_I,_I},         1,{_I}},
    [IMP_FILE_DELETE]    = {"file_delete",          2,{_I,_I},         1,{_I}},
    [IMP_FILE_RENAME]    = {"file_rename",          4,{_I,_I,_I,_I},   1,{_I}},
    [IMP_FILE_MKDIR]     = {"file_mkdir",           2,{_I,_I},         1,{_I}},
    [IMP_FILE_RMDIR]     = {"file_rmdir",           2,{_I,_I},         1,{_I}},
    [IMP_GET_EPOCH_MS]   = {"get_epoch_ms",         0,{},              1,{WASM_I64}},
    [IMP_GET_UPTIME_MS]  = {"get_uptime_ms",        0,{},              1,{WASM_I64}},
    [IMP_GET_LAST_COMM_MS]={"get_last_comm_ms",     0,{},              1,{WASM_I64}},
    [IMP_PRINT_I64]      = {"print_i64",            1,{WASM_I64},      0,{}},
    [IMP_PRINT_F64]      = {"print_f64",            1,{WASM_F64},      0,{}},
    [IMP_HOST_SNPRINTF]  = {"host_snprintf",        4,{_I,_I,_I,_I},   1,{_I}},
    [IMP_SIN]            = {"sin",                  1,{_D},            1,{_D}},
    [IMP_COS]            = {"cos",                  1,{_D},            1,{_D}},
    [IMP_TAN]            = {"tan",                  1,{_D},            1,{_D}},
    [IMP_ASIN]           = {"asin",                 1,{_D},            1,{_D}},
    [IMP_ACOS]           = {"acos",                 1,{_D},            1,{_D}},
    [IMP_ATAN]           = {"atan",                 1,{_D},            1,{_D}},
    [IMP_ATAN2]          = {"atan2",                2,{_D,_D},         1,{_D}},
    [IMP_POW]            = {"pow",                  2,{_D,_D},         1,{_D}},
    [IMP_EXP]            = {"exp",                  1,{_D},            1,{_D}},
    [IMP_LOG]            = {"log",                  1,{_D},            1,{_D}},
    [IMP_LOG2]           = {"log2",                 1,{_D},            1,{_D}},
    [IMP_FMOD]           = {"fmod",                 2,{_D,_D},         1,{_D}},
};
#undef _I
#undef _F
#undef _D

uint8_t imp_used[IMP_COUNT];
