' GPS API smoke test
LAT# = GPSLAT#()
LON# = GPSLON#()
ALT# = GPSALT#()
SP# = GPSSPEED#
DR# = GPSDIR#
DIST# = ORIGINDIST#
ANG# = ORIGINANGLE#

VALID = HASGPS
ORG = HASORIGIN
ALT_I = GPSALT
SP_I = GPSSPEED

FORMAT "& & & & & & &", LAT#, LON#, ALT#, SP#, DR#, DIST#, ANG#
FORMAT "% % % %", VALID, ORG, ALT_I, SP_I
