' Mutual recursion via DECLARE
DECLARE FUNCTION IS_ODD N

FUNCTION IS_EVEN N
  IF N = 0 THEN RETURN -1
  RETURN IS_ODD(N - 1)
END FUNCTION

FUNCTION IS_ODD N
  IF N = 0 THEN RETURN 0
  RETURN IS_EVEN(N - 1)
END FUNCTION

FOR I = 0 TO 5
  FORMAT "% even=% odd=%", I, IS_EVEN(I), IS_ODD(I)
NEXT
